version: "3.8"

services:
  bruhbot:
    image: "bruhbot:prod"
    build:
      context: "."
      dockerfile: "Dockerfile"
    networks:
      - "production"
    restart: "on-failure"
    ports: 
      - "8000:8000"
    environment: 
      - NODE_ENV=production
      - PORT=8000

networks:
  production:
    external: true