version: '3.8'

services: 
    db:
        container_name: discordbot
        image: mongo
        ports:
            - '${DOCKER_MONGO_PORT}:${DOCKER_MONGO_PORT}'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${DOCKER_MONGO_DATABASE}
            MONGO_USERNAME: ${DOCKER_MONGO_USERNAME}
            MONGO_PASSWORD: ${DOCKER_MONGO_PASSWORD}
        volumes:
            - ./data/db
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro