version: '3.8'

services: 
    db:
        image: mongo
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: bj4RTRXSJyxrv8M3
            MONGO_INITDB_DATABASE: discordbot
            MONGO_USERNAME: discordbot-admin
            MONGO_PASSWORD: bj4RTRXSJyxrv8M3
        volumes:
            - ./data/db
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro