import dotenv from 'dotenv'

dotenv.config()

export const {
    NODE_ENV,
    PORT,
    MONGO_USERNAME,
    MONGO_PASSWORD,
    MONGO_HOST,
    MONGO_PORT,
    MONGO_DATABASE,
    MONGODB_PRODUCTION_URL,
    NGROK_AUTHTOKEN,
    LOCALXPOSE_ACCESS_TOKEN,
    LOCALXPOSE_SUBDOMAIN,
    DISCORD_CHANNEL_WEBHOOK,
    TWITCH_CLIENT_ID,
    TWITCH_CLIENT_SECRET,
    YOUTUBE_API_KEY,
    DISCORD_BOT_TOKEN,
    TWITCH_HUB_CALLBACK,
    BOT_NAME,
} = process.env